/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ActCards: () => import('#controllers/act_cards_controller'),
  Config: () => import('#controllers/config_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Mds: () => import('#controllers/mds_controller'),
  MeshSessions: () => import('#controllers/mesh_sessions_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  Queues: () => import('#controllers/queues_controller'),
  Session: () => import('#controllers/session_controller'),
  SessionNotifications: () => import('#controllers/session_notifications_controller'),
  SessionOps: () => import('#controllers/session_ops_controller'),
  Targets: () => import('#controllers/targets_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
  Terminals: () => import('#controllers/terminals_controller'),
  Tools: () => import('#controllers/tools_controller'),
}
